### ISSUE TITLE
Use latest version for packages in generated modules

### ISSUE THREAD

**Issue by Francois-Esquire** [americanexpress/one-app-cli#29]
# 💡 Feature request

I would like to use the `latest` tagged version in the preset dependencies generated by `generator-one-app-module`.

## Is your feature request related to a problem? Please describe

Using the `latest` tag published will align best with the documentation of a package, can fall out of sync. 

## Describe the solution you'd like

We can use `npm show {package} version` to pull the `latest` tag and apply that. Possibly cap at major releases to preserve some consistency.

**Comment by anescobar1991** [comment]
What would fall out of sync? Since the dependency versions in `package.json` use the caret (^) any time a user runs the generator they will get the latest version of each package within the pinned down major version.

If we have it use latest we will have no way of controlling downstream dependencies' breaking changes leaking into our users' modules upon generation.
